# version: '3.8'  # Yeh line rakho, warning aayegi but chalta hai
services:
  postgres:
    image: postgres:13
    container_name: fitpro_postgres
    environment:
      POSTGRES_USER: fitpro
      POSTGRES_PASSWORD: fitpro_password
      POSTGRES_DB: fitpro_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fitpro_network

  mongodb:
    image: mongo:5
    container_name: fitpro_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: fitpro
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - fitpro_network

  redis:
    image: redis:6-alpine
    container_name: fitpro_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fitpro_network

volumes:
  postgres_data:
  mongo_data:
  redis_data:

networks:
  fitpro_network:
    driver: bridge